tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "romkatv/powerlevel10k"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "ata"
brew "python@3.12"
brew "gnutls"
brew "cask"
brew "docker"
brew "docker-compose"
brew "openjpeg"
brew "leptonica"
brew "ffmpeg"
brew "gcc"
brew "geometry"
brew "gh"
brew "ghostscript"
brew "git"
brew "gnu-getopt"
brew "librsvg"
brew "graphviz"
brew "gyb"
brew "helm"
brew "htop"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "librdkafka"
brew "kcat"
brew "mas"
brew "midnight-commander"
brew "yt-dlp"
brew "mpv"
brew "nmap"
brew "openjdk"
brew "openssh"
brew "pandoc"
brew "pgcli"
brew "pgformatter"
brew "plantuml"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "speedtest-cli"
brew "starship"
brew "transmission-cli"
brew "typst"
brew "watch"
brew "wifi-password"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password-cli"
cask "alt-tab"
cask "amazon-q"
cask "appcleaner"
cask "arc"
cask "bartender"
cask "cheatsheet"
cask "cleanmymac"
cask "diffusionbee"
cask "discord"
cask "dotnet-sdk"
cask "drawio"
cask "dropbox"
cask "font-hack-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "forklift"
cask "github"
cask "gitkraken"
cask "grammarly"
cask "grandperspective"
cask "handbrake"
cask "iterm2"
cask "jetbrains-toolbox"
cask "latest"
cask "linearmouse"
cask "lm-studio"
cask "logi-options+"
cask "logitune"
cask "mactex"
cask "macwhisper"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mimestream"
cask "mongodb-compass"
cask "mono-mdk-for-visual-studio"
cask "obsidian"
cask "pdf-expert"
cask "pgadmin4"
cask "raycast"
cask "readdle-spark"
cask "rocket"
cask "setapp"
cask "sf-symbols"
cask "shottr"
cask "skype-for-business"
cask "spotify"
cask "teamviewer"
cask "tower"
cask "vanilla"
cask "visual-studio-code"
cask "warp"
cask "yubico-yubikey-manager"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Craft", id: 1487937127
mas "DaisyDisk", id: 411643860
mas "Disk Speed Test", id: 425264550
mas "Easy CSV Editor", id: 1171346381
mas "Gemini 2", id: 1090488118
mas "Grammarly for Safari", id: 1462114288
mas "iNet Network Scanner", id: 403304796
mas "JSON Editor", id: 567740330
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Magnet", id: 441258766
mas "Messenger", id: 1480068668
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "OmniGraffle", id: 1142578753
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Paste", id: 967805235
mas "Patterns", id: 429449079
mas "Permute 3", id: 1444998321
mas "Photomator", id: 1444636541
mas "Pixelmator Pro", id: 1289583905
mas "PLIST Editor", id: 1157491961
mas "Reeder", id: 1529448980
mas "Speedtest", id: 1153157709
mas "SSH Config Editor", id: 1109319285
mas "Super Agent", id: 1568262835
mas "Symbolic Linker", id: 1435106536
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "TimeStory", id: 1470702823
vscode "aaron-bond.better-comments"
vscode "amazonwebservices.codewhisperer-for-command-line-companion"
vscode "bradymholt.pgformatter"
vscode "britesnow.vscode-toggle-quotes"
vscode "chrischinchilla.vscode-pandoc"
vscode "codezombiech.gitignore"
vscode "docsmsft.docs-markdown"
vscode "eamodio.gitlens"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.todo-tree"
vscode "hediet.vscode-drawio"
vscode "ibm.output-colorizer"
vscode "idleberg.icon-fonts"
vscode "ionide.ionide-fsharp"
vscode "james-yu.latex-workshop"
vscode "jebbs.plantuml"
vscode "jerryhong.autofilename"
vscode "jmrog.vscode-nuget-package-manager"
vscode "kzvi.pandoc-markdown-preview"
vscode "liamhammett.inline-parameters"
vscode "mechatroner.rainbow-csv"
vscode "melishev.feather-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-pack"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-dotnettools.vscodeintellicode-csharp"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-repositories"
vscode "nvarner.typst-lsp"
vscode "orangex4.vscode-typst-sync"
vscode "patcx.vscode-nuget-gallery"
vscode "piotrpalarz.vscode-gitignore-generator"
vscode "pkief.material-icon-theme"
vscode "pnp.polacode"
vscode "quicktype.quicktype"
vscode "redhat.vscode-yaml"
vscode "reflectiondm.classynaming"
vscode "renesaarsoo.sql-formatter-vsc"
vscode "richie5um2.vscode-sort-json"
vscode "s3anmorrow.openwithkraken"
vscode "sidiandi.plantuml-sidiandi-fork"
vscode "spikespaz.vscode-smoothtype"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-danish"
vscode "surv.typst-math"
vscode "tintoy.msbuild-project-tools"
vscode "tomoki1207.pdf"
vscode "vscode-icons-team.vscode-icons"
vscode "yzane.markdown-pdf"
vscode "yzhang.dictionary-completion"
vscode "yzhang.markdown-all-in-one"
