node.rules = [
    {
        matches = [{ node.name = "alsa_output.usb-Sonos__Inc._Sonos_Ace__USB__000000000010-00.analog-stereo" }]
        actions = { update-props = { node.description = "Sonos Ace"  node.nick = "Sonos Ace" } }
    }
    {
        matches = [{ node.name = "alsa_output.usb-Sonos__Inc._Sonos_Ace__USB__000000000010-00.iec958-stereo" }]
        actions = { update-props = { node.description = "Sonos Ace"  node.nick = "Sonos Ace" } }
    }
    {
        matches = [{ node.name = "alsa_input.usb-Sonos__Inc._Sonos_Ace__USB__000000000010-00.mono-fallback" }]
        actions = { update-props = { node.description = "Sonos Ace Mic"  node.nick = "Sonos Ace Mic" } }
    }
    {
        matches = [{ node.name = "alsa_output.usb-Sennheiser_BTD_700_09B88CA9D63469AB3C08-02.analog-stereo" }]
        actions = { update-props = { node.description = "Sennheiser BTD 700"  node.nick = "Sennheiser BTD 700" } }
    }
    {
        matches = [{ node.name = "alsa_output.usb-Sennheiser_BTD_700_09B88CA9D63469AB3C08-02.iec958-stereo" }]
        actions = { update-props = { node.description = "Sennheiser BTD 700 Digital"  node.nick = "Sennheiser BTD 700 Digital" } }
    }
    {
        matches = [{ node.name = "alsa_input.usb-Sennheiser_BTD_700_09B88CA9D63469AB3C08-02.mono-fallback" }]
        actions = { update-props = { node.description = "Sennheiser BTD 700 Mic"  node.nick = "Sennheiser BTD 700 Mic" } }
    }
]
